"""empty message

Revision ID: 22bafde64223
Revises: 43a4c831b645
Create Date: 2021-02-01 16:59:24.180679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bafde64223'
down_revision = '43a4c831b645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
